### ISSUE TITLE
Hachoir Installation on Win 10 Python 3.5.2

### ISSUE THREAD

**Issue by fatiharaci** [fatiharaci/Spring2017Swe573#9]
Installing Hachoir giving following error:

Collecting hachoir-core
  Using cached hachoir-core-1.3.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\araci\AppData\Local\Temp\pip-build-iw0dyepk\hachoir-core\setup.py", line 41
        **print "Sorry, you need Python 2.4 or greater to run (install) Hachoir!"**
                                                                              ^
    SyntaxError: invalid syntax

**Comment by fatiharaci** [comment]
Hachoir requires python2; and 3 exceeds limitation. Installing 2.7 may solve the problem:

**Comment by fatiharaci** [comment]
![image](https://cloud.githubusercontent.com/assets/17599008/23217613/954b6c54-f922-11e6-8747-2e52b7f61fdd.png)



Python Still See 3.5.2 try to change it to 2.7

**Comment by fatiharaci** [comment]
There is no solution this problem on windows. 

Alternative environment is designed using ubuntu.
